language: ruby
rvm:
  - 1.9.3
  - 2.1.1
env:
  - DB=sqlite
  - DB=pgsql
bundler_args: "--without development"
before_script:
  - psql -c "CREATE USER katoy WITH PASSWORD 'katoy';" -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate
  - RAILS_ENV=test bundle exec rake test
  - RAILS_ENV=test bundle exec rake spec
