language: ruby
rvm:
  - 1.9.3
  - 2.1.1
env:
  - DB=sqlite
  - DB=pgsql
bundler_args: "--without development"
before_script:
  - sqlite -e "cp config/database.yml-sqlite3 config/database.yml"
  - pgsql -e "psql -c 'create database travis_ci_test;' -U postgres"
  - pgsql -e "cp config/database.yml.travis-pgsql config/database.yml"
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate
  - RAILS_ENV=test bundle exec rake test
  - RAILS_ENV=test bundle exec rake spec
